[package]
name = "pixelstrom"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.6", features = ["ws"] }
tokio = { version = "1", features = ["full"] }
prost = "0.11"
tower-http = { version = "0.4", features = ["fs"] }
tokio-tungstenite = "0.18"
rand = "0.8.5"
tracing = "0.1"
tracing-subscriber = "0.3"
colorgrad = "0.7.0"

[build-dependencies]
prost-build = "0.13"
