[package]
name = "pixelstrom"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.6", features = ["ws"] }
colorgrad = "0.7"
prost = "0.11"
rand = "0.8.5"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.4", features = ["fs"] }
tracing = "0.1"
tracing-subscriber = "0.3"

[build-dependencies]
prost-build = "0.13"
